# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'XCDYouTubeKit', '~> 2.8'

target 'sacred' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sacred


  target 'sacredTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sacred-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sacred-tvOS

  target 'sacred-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
